apiVersion: v1
kind: ResourceQuota
metadata:
  name: skattjakt-quota
  namespace: skattjakt
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    requests.storage: 100Gi
    persistentvolumeclaims: "6"
    count/deployments.apps: "10"
    count/statefulsets.apps: "4"
    count/jobs.batch: "20"
    services.loadbalancers: "1"
