apiVersion: v1
kind: ResourceQuota
metadata:
  name: skattjakt-quota
  namespace: skattjakt
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    requests.storage: 200Gi
    persistentvolumeclaims: "8"
    count/deployments.apps: "10"
    count/statefulsets.apps: "4"
    count/jobs.batch: "20"
    services.loadbalancers: "1"
